# Generated by Django 2.2.3 on 2019-07-05 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ForecastApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='forecast',
            name='wind_speed',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='forecast',
            name='pub_date',
            field=models.DateField(),
        ),
    ]
