# Generated by Django 2.2.3 on 2019-07-05 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ForecastApp', '0002_auto_20190705_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='forecast',
            name='rain',
            field=models.BooleanField(default=False),
        ),
    ]
